<?php

namespace ServerControllerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServerInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerInfoRepository extends EntityRepository
{
}
