server_controller_serverinfo:
    resource: "@ServerControllerBundle/Resources/config/routing/serverinfo.yml"
    prefix:   /serverinfo

server_controller:
    resource: "@ServerControllerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
